export const HOME = '/home'
export const LOGIN = '/login'
export const SIGNUP = '/signup'
export const PRIMERCOMPONENTE = '/primercomponente'
export const SEGUNDOCOMPONENTE = '/segundocomponente'
export const TERCERCOMPONENTE = '/tercercomponente'